
USER_LIB_PATH=$(shell pwd)/../libraries

BOARD_TAG    = uno
ARDUINO_LIBS = SoftwareSerial Akeru TinyGPS
ARDUINO_PORT = /dev/ttyUSB0
MONITOR_PORT = /dev/ttyUSB0

include /usr/share/arduino/Arduino.mk
